Homeworks
bsipocz/ASTR497 pull request #5
Opened 2021-04-30 21:40 UTC by maria8ch

HW 1 pull, with all questions completed (to the best of my ability).

2021-05-07 21:11 UTC, bsipocz requested changes
Two minor things:

* Please do remove the notebook from the submission.

`git rm HR_draft.ipynb` should do the trick.

* Please move it under `assignments/homework/`, after you created a directory for you in there.  Do the move with `git mv `.

Then commit the changes, push to github.

2021-05-15 02:05 UTC, maria8ch commented
@bsipocz I have made the edits you have requested, hopefully correctly :)

2021-05-21 06:01 UTC, bsipocz approved these changes
I've left a few minor tips and advices, otherwise, the solutions are correct and the code is nice and clean.

Thank you!

2021-05-21 06:01 UTC, bsipocz commented on assignments/homework/chernyavskaya/497hw1.py
> +plt.ylabel('MJ/ kg', fontsize=12);
You don't need these two lines, the point of using Quantities and enabling `quantity_support()` above is that matplotlib is able to handle quantities, including adding the correct labels to the axes.

https://docs.astropy.org/en/stable/visualization/matplotlib_integration.html#plotting-quantities

2021-05-21 06:01 UTC, bsipocz commented on assignments/homework/chernyavskaya/497hw1.py
> +import astroplan as ap
no big deal, but it's a nice practice to only import things you use. 
If you work in an editor or an IDE (as opposed to the browser with notebooks), then there are nice plugins for checking codestyle and will notify you about these.

Here are the python style recommendations (often just called PEP8): https://www.python.org/dev/peps/pep-0008/
(but not everything in pep8 make sense!)

And tools such as `flake8`, `pycodestyle`, etc would do the codecheck, and tools like `autopep8` would apply some automated fixes.

2021-05-21 06:01 UTC, bsipocz commented on assignments/homework/chernyavskaya/497hw1.py
> +now_string = Time(now, format='iso', precision=6);
you don't necessarily need to create a  new `Time` here, you can change the precision of the previous one as:

`now.precision = 6`

2021-05-21 06:01 UTC, bsipocz commented on assignments/homework/chernyavskaya/497hw1.py
> +    return
No need to return `None`, it is the default behaviour of Python

2021-05-21 06:01 UTC, merged